# Actions: Custom applications to perform complex, frequently repeated tasks.
name: 04 - Using Actions

on:
    # push:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: using-actions/react-app
        steps:
            # 1. Checkout the code from the repository
            - name: Checkout code
              uses: actions/checkout@v4
            # 2. Install dependencies of our react application
            - name: Printing folder structure
              run: ls
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
            - name: Install dependencies
              run: npm ci
              # working-directory: using-actions/react-app
            # 3. Execute automated tests
            - name: Run unit tests
              run: npm run test
              # working-directory: using-actions/react-app
