name: 07 - Expressions

## Providing a default: ${{ expression || default_value }}. The default_value will be used if the expression evaluates to a falsy value.
## Using the ternary operation: ${{ expression && truthy_value || falsy_value }}.
#       The truthy_value will be used if the expression evaluates to a truthy value, and the falsy_value will be used otherwise.
#       The actual value resulting from the expression evaluation will not be present in the result of this ternary operation.
run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF' }}

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] Print start-up data"
        # To execute jobs and steps conditionally, we can leverage the if keyword in either the job or the step definition.
        # Already evaluated as an expression (does not need ${{}})
        if: inputs.debug
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"
      - name: "[debug] Print when triggered from main"
        # # To execute jobs and steps conditionally, we can leverage the if keyword in either the job or the step definition.
        # Already evaluated as an expression (does not need ${{}})
        if: inputs.debug && github.ref == 'refs/heads/main'
        run: echo "I was triggered from main"
      - name: Greeting
        run: echo "Hello, world"
