name: 13 - Using Caching

# $ cd 13-cahing
# $ npx create-react-app --template typescript react-app
# $ cd react-app
# $ npm run start

on:
    workflow_dispatch:
        inputs:
            use-cache:
                description: Whether to execute cache step
                type: boolean
                default: true
            node-version:
                description: Node version
                type: choice
                options:
                    - 18.x
                    - 20.x
                    - 21.x
                default: 20.x

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 13-caching/react-app
        steps:
            # 1. Checkout the code
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ inputs.node-version }}
            - name: Download cached dependencies
              id: cache-npm
              uses: actions/cache@v4
              if: ${{ inputs.use-cache }}
              with:
                  path: 13-caching/react-app/node_modules
                  key: deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}
            # 2. Install dependencies
            - name: Install dependencies
              if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
              run: npm ci
            # 3. Unit testing and building
            - name: Testing
              run: npm run test
            - name: Building
              run: npm run build
            # 4. Deploy to a nonprod environment
            - name: Deploying to nonprod
              run: echo "Deploying to nonprod"
